# Generated by Django 5.1 on 2024-08-25 04:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, unique=True, verbose_name='slug')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('expenses_total', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='despesas totais')),
                ('revenues_total', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='receitas totais')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='saldo')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
